import { ArrowLongRightIcon, CloudIcon, CircleStackIcon, CpuChipIcon, ShieldCheckIcon } from "@heroicons/react/24/outline";
import { Container } from "../components/Container";
import { Connect } from "../components/Connect";
import { RelatedInsights } from "../components/LandingSEOSections";
import { ProductFAQ, ProductRelatedLinks, ProductSEO } from "../components/ProductSEOSections";
import { SectionLink } from "../components/SectionLink";
import "./products.css";
import "./products-theme.css";
import { useCmsProduct } from "../cms/hooks";
import { CmsProductSections } from "../cms/CmsProductSections";
import { hasCmsProductContent } from "../cms/types";

const environments = ["Cloud", "Hybrid", "On-premise", "Edge"];
const standards = ["Apache Iceberg", "Delta Lake", "Hudi"];
const foundations = [
  { icon: CircleStackIcon, name: "DataOps", detail: "Bring data operations together." },
  { icon: CpuChipIcon, name: "AI / ML", detail: "Connect data to intelligent workloads." },
  { icon: ShieldCheckIcon, name: "Governance", detail: "Keep control close to the data." },
];
const relatedLinks = [
  { href: "/data-engineering-ai-foundations", title: "Data Engineering & AI Foundations", description: "Build the data pipelines and foundations behind intelligent workloads." },
  { href: "/cloud-infrastructure-ai-compute", title: "Cloud Infrastructure & AI Compute", description: "Connect data platforms to flexible enterprise infrastructure." },
  { href: "/products/dci-360", title: "DCI 360", description: "See how infrastructure teams monitor data center operations." },
];
const faqs = [
  { question: "What is i-Lakehouse?", answer: "i-Lakehouse is a hybrid-native data platform that brings DataOps, AI/ML and cloud workloads into one connected foundation." },
  { question: "Where can i-Lakehouse operate?", answer: "i-Lakehouse supports cloud, hybrid, on-premise and edge environments." },
  { question: "Which open data formats are included?", answer: "Its open data foundation highlights Apache Iceberg, Delta Lake and Hudi, alongside security, lineage and compliance controls." },
  { question: "Who is i-Lakehouse for?", answer: "It is positioned for data-platform, analytics, and AI teams that need to connect enterprise sources while retaining governance and deployment choice." },
  { question: "Does every workload have to move at once?", answer: "No. A practical adoption path starts with a defined data product, maps its source and access rules, and expands as quality and operating ownership are established." },
];

export function ILakehouse() {
  const cmsEntry = useCmsProduct();
  return (
    <main className={`product-page lake-page ${hasCmsProductContent(cmsEntry) ? "cms-has-content" : ""}`}>
      <ProductSEO pageKey="iLakehouse" cmsEntry={cmsEntry} />
      <section className="product-hero lake-hero" style={cmsEntry?.hero_image ? { backgroundImage: `url(${cmsEntry.hero_image})` } : undefined}><Container className="lake-hero-layout"><div className="lake-hero-copy"><p className="product-eyebrow">HYBRID-NATIVE DATA PLATFORM</p><h1>{cmsEntry?.hero_title || cmsEntry?.title || "i-Lakehouse"}</h1><p className="product-hero-subtitle">{cmsEntry?.hero_description || <>The Hybrid-Native<br />Intelligent Data Platform</>}</p><p className="product-hero-intro">{cmsEntry?.summary || "Connect DataOps, AI/ML and governed data across cloud, on-premise and edge."}</p><a className="product-button lake-button" href={cmsEntry?.cta_url || "#lake-intelligence"}>{cmsEntry?.cta_text || "Explore the platform"} <ArrowLongRightIcon aria-hidden="true" /></a></div><div className="lake-hero-visual" role="img" aria-label="Conceptual data flow connecting Data, AI and Cloud with cloud, on-premise and edge environments"><div className="lake-visual-kicker">ONE CONNECTED FOUNDATION</div><div className="lake-hero-nodes"><div><CircleStackIcon aria-hidden="true" /><strong>DATA</strong></div><span className="lake-connector" /><div><CpuChipIcon aria-hidden="true" /><strong>AI</strong></div><span className="lake-connector" /><div><CloudIcon aria-hidden="true" /><strong>CLOUD</strong></div></div><div className="lake-hero-orbit"><span>ON-PREMISE</span><i /><span>HYBRID</span><i /><span>EDGE</span></div></div></Container><div className="lake-hero-rule" /></section>
      <CmsProductSections entry={cmsEntry} />
      <section className="product-section product-copy-section"><Container className="product-copy-layout"><div><p className="product-eyebrow">THE DATA PROBLEM</p><h2>One foundation for usable enterprise data.</h2></div><div><p>i-Lakehouse is Turbo AI's hybrid-native data platform concept for data engineering, analytics, and AI teams. It addresses fragmented sources, inconsistent quality, and disconnected workloads by bringing integration, DataOps, governance, and AI/ML access into a shared architectural approach.</p><p>The goal is not to move every dataset to one place. It is to give important data products clear ownership, traceable transformations, and controlled access across cloud, hybrid, on-premise, and edge environments where those choices are appropriate.</p></div></Container></section>
      <section id="lake-intelligence" className="product-section lake-intelligence"><Container><div className="product-section-intro"><p className="product-eyebrow">01 / UNIFIED INTELLIGENCE</p><h2>Data, AI and cloud.<br /><span>Working as one.</span></h2></div><div className="lake-equation"><span>DATA</span><b>+</b><span>AI / ML</span><b>+</b><span>CLOUD</span><ArrowLongRightIcon aria-hidden="true" /><strong>INTELLIGENCE</strong></div></Container></section>
      <section className="product-section product-copy-section product-copy-alt"><Container><p className="product-eyebrow">OPERATING ARCHITECTURE</p><h2>From sources to governed use.</h2><div className="product-copy-grid"><article><h3>Integrate and prepare</h3><p>Connect approved enterprise sources through batch or streaming patterns suited to the workload. Validate freshness, schema, and quality before a dataset is treated as reliable.</p></article><article><h3>Operate with DataOps</h3><p>Version pipelines, document transformations, monitor failures, and assign data-product ownership. A repeatable process helps teams correct broken inputs before downstream analysis is affected.</p></article><article><h3>Support AI and analytics</h3><p>Make governed data available to analytics and AI/ML workloads with consistent definitions. Model evaluation and application decisions remain separate from the storage foundation.</p></article><article><h3>Govern across environments</h3><p>Apply access, lineage, retention, and security controls wherever the data runs. Hybrid placement is a design choice shaped by latency, privacy, operational cost, and existing systems.</p></article></div></Container></section>
      <section className="product-section lake-deploy"><Container><div className="product-section-heading"><div><p className="product-eyebrow">02 / DEPLOY ANYWHERE</p><h2>Built for your environment.</h2></div><p>Cloud, hybrid, on-premise and edge.</p></div><div className="lake-deploy-map"><div className="lake-platform">i-Lakehouse <span>ONE PLATFORM</span></div><div className="lake-deploy-lines" aria-hidden="true" /><div className="lake-environments">{environments.map((environment, index) => <div key={environment}><span>0{index + 1}</span><strong>{environment}</strong></div>)}</div></div></Container></section>
      <section className="product-section lake-open"><Container className="lake-open-layout"><div><p className="product-eyebrow">03 / OPEN DATA FOUNDATION</p><h2>Choice stays open.</h2><p>Open standards support a flexible data foundation and reduce vendor lock-in.</p></div><div className="lake-standard-list">{standards.map((standard, index) => <div key={standard}><span>0{index + 1}</span><strong>{standard}</strong><ArrowLongRightIcon aria-hidden="true" /></div>)}</div></Container></section>
      <section className="product-section lake-realtime"><Container><div className="product-section-heading"><div><p className="product-eyebrow">04 / REAL-TIME INTELLIGENCE</p><h2>From streams to insight.</h2></div><p>Streaming and analytics technologies in one ecosystem.</p></div><div className="lake-stream" aria-label="Conceptual technology flow: Kafka, streaming, Spark/Flink/Trino, analytics and AI"><span>Kafka</span><ArrowLongRightIcon aria-hidden="true" /><span>Streaming</span><ArrowLongRightIcon aria-hidden="true" /><span>Spark / Flink / Trino</span><ArrowLongRightIcon aria-hidden="true" /><strong>Analytics / AI</strong></div><p className="product-concept-label">CONCEPTUAL TECHNOLOGY FLOW</p></Container></section>
      <section className="product-section lake-foundations"><Container><p className="product-eyebrow">05 / THE OPERATING FOUNDATION</p><h2>Built for enterprise data work.</h2><div className="lake-foundation-grid">{foundations.map(({ icon: Icon, name, detail }) => <article key={name}><Icon aria-hidden="true" /><h3>{name}</h3><p>{detail}</p></article>)}</div></Container></section>
      <section className="product-section lake-trust"><Container className="lake-trust-layout"><div><p className="product-eyebrow">06 / TRUST BY DESIGN</p><h2>Know where data goes.<br /><span>Keep it governed.</span></h2></div><div className="lake-trust-visual"><div>SECURITY</div><span /><div>LINEAGE</div><span /><div>COMPLIANCE</div></div></Container></section>
      <section className="product-section product-copy-section"><Container><p className="product-eyebrow">ENTERPRISE APPLICATION</p><h2>Built around real data products.</h2><div className="product-copy-grid"><article><h3>Operational analytics</h3><p>Combine source events and reference data into a timely view with documented definitions. Teams can inspect why a metric changed and how recently its inputs arrived.</p></article><article><h3>AI-ready knowledge</h3><p>Prepare permitted documents and records for retrieval-based assistants. Ownership, access boundaries, and lineage help keep generated answers grounded in approved information.</p></article><article><h3>Hybrid data access</h3><p>Workloads can be placed according to data locality, latency, and governance needs. The architecture supports evaluating cloud, on-premise, and edge patterns without asserting that every deployment is identical.</p></article><article><h3>Adoption path</h3><p>Start with one bounded data product: identify users, sources, quality checks, access rules, and a measurable decision. Expand only when operations and ownership are established.</p></article></div></Container></section>
      <section className="product-section product-copy-section product-copy-alt"><Container className="product-copy-layout"><div><p className="product-eyebrow">OUTCOMES AND DIFFERENTIATION</p><h2>Open data, governed operation, deployment choice.</h2></div><div><p>i-Lakehouse is designed to help teams create reusable data products with clearer quality, lineage, ownership, and access. That can reduce repeated integration work, improve confidence in analytics, and give AI applications a more dependable source foundation.</p><p>Its differentiator is the relationship among DataOps, AI/ML, governance, and hybrid-native deployment. Open table formats support data portability, while the operating model keeps security, lineage, and compliance close to the data. Actual architecture and integrations are validated for each environment.</p></div></Container></section>
      <ProductRelatedLinks links={relatedLinks} />
      <RelatedInsights slugs={["energy-ai-asset-intelligence-foundations", "data-centre-capacity-intelligence", "manufacturing-predictive-maintenance-workflow"]} title="Data-platform and operational intelligence insights" intro="Explore how governed data foundations support asset, capacity, and manufacturing decisions." />
      <ProductFAQ title="i-Lakehouse questions" intro="The essentials of its hybrid-native, open data approach." items={faqs} />
      <section className="product-cta lake-cta"><Container><p className="product-eyebrow">i-LAKEHOUSE</p><h2>Bring your data and AI together.</h2><SectionLink href="#connect" className="product-button lake-button">Start a conversation <ArrowLongRightIcon aria-hidden="true" /></SectionLink></Container></section>
      <Connect />
    </main>
  );
}
